FROM scratch

ADD https://github.com/grafana/grafana-infinity-datasource/releases/download/v2.9.6/yesoreyeram-infinity-datasource-2.9.6.darwin_amd64.zip /grafana/plugins/yesoreyeram-infinity-datasource-2.9.6.darwin_amd64.zip
